<?php

/**
 * Team
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Team extends BaseTeam
{
    private $_teamName;

    public function getTeamName() {
        if ( $this->_teamName == "" ) {
            $player1 = Player::getPlayerById( $this->teammate1_id );
            $player2 = Player::getPlayerById( $this->teammate2_id );
            $this->_teamName = "{$player1->fname} {$player1->sname}/{$player2->fname} {$player2->sname}";
        }
        return $this->_teamName;
    }

    public static function getTourId( $id ) {
        $tour_id = Doctrine_Query::create()
                    ->select( 'Tournaments_id')
                    ->from( 'Team' )
                    ->where( 'id = ' . $id )
                    ->execute( array(), DOCTRINE_CORE::HYDRATE_SINGLE_SCALAR);
        if ( !$tour_id ) {
            return false;
        }

        return $tour_id;
    }

    public static function getById( $id ) {
        //$Tournaments_id = self::getTourId( $id );
        return Doctrine_Core::getTable( 'Team' )->findOneBy('id', $id);// findByIdAndTournaments_id( $id, $Tournaments_id );
    }

    public function getAll() {
        return $this->getTable()->findAll();
    }

    public function withdrawTeam() {
        Doctrine_Query::create()
            ->delete( 'Rank' )
            ->where( 'Tournaments_id = ' . $this->Tournaments_id . ' and Players_id in ( ' . $this->teammate1_id . ', ' . $this->teammate2_id . ')' )
            ->execute();
        $this->delete();
    }
}