<div id="content">
    <div id="pad">
        <?php echo isset( $this->pageContent->content ) ? $this->pageContent->content : null; ?>
    </div>
</div>
<div id="sidebar">
    <div class="widget">
        <h2>O szkole</h2>
        <ul id="submenu">
            <li><a href="/pages/kadra.html">Kadra pedagogiczna</a></li>
            <li><a href="/pages/uczniowie.html">Uczniowie</a></li>
            <li><a href="/pages/obiekty.html">Obiekty sportowe</a>
                <ul>
                    <li><a href="/pages/boiska_plazowe.html">Boiska</a></li>
                    <li><a href="/pages/boiska_pod_balonem.html">Boiska pod balonem</a></li>
                    <li><a href="/pages/szkola.html">Szkoła</a></li>
                    <li><a href="/pages/odnowa_biologiczna.html">Odnowa biologiczna</a></li>
                    <li><a href="/pages/basen.html">Basen</a></li>
                    <li><a href="/pages/silownia.html">Siłownia</a></li>
                </ul>
            </li>
            <li><a href="/pages/absolwenci.html">Absolwenci</a></li>
        </ul>
    </div>
</div>