<div id="footer">
<?php echo $this->navigation()
            ->menu()
            ->setMaxDepth(0)
            ->setUlClass('footer-menu')
        ?>
    <div id="footer-copywright">
            Copyright by <a href="http://webbers.pl">webbers.pl</a>
    </div><!-- end footer-copywright -->
<!--
		<ul id="footer-rss-social">
			<li><a href=""><img src="img/social-icons/twitter_16.png" alt="Twitter"/></a></li>
			<li><a href=""><img src="img/social-icons/facebook_16.png" alt="Facebook"/></a></li>
			<li><a href=""><img src="img/social-icons/flickr_16.png" alt="Flickr"/></a></li>
			<li><a href=""><img src="img/social-icons/rss_16.png" alt="RSS"/></a></li>
		</ul>
-->

</div><!-- end footer -->