<!-- FOOTER (start) -->

<div id="footer-top" class="ie6"><!-- --></div>
<div id="footer-widget-area" class="ie6">
        <div id="footer-widget-area-inner" class="ie6">
                
                <div class="widget">
                        <div class="pad">
                            <h3>O naszej szkole</h3>
                            <ul>
                                <li><a href="/pages/kadra.html">Kadra pedagogiczna</a></li>
                                <li><a href="/pages/uczniowie.html">Uczniowie</a></li>
                                <li><a href="/pages/obiekty.html">Obiekty</a></li>
                                <li><a href="/pages/absolwenci.html">Absolwenci</a></li>
                            </ul>

                        </div><!-- .pad (end) -->
                </div><!-- .widget (end) -->
               <div class="widget">
                        <div class="pad">
                            <h3>Dla naszych uczniów</h3>
                           <ul>
                                <li><a href="/pages/plan_zajec.html">Plan zajęć</a></li>
                                <li><a href="/pages/druki.html">Druki</a></li>
                                <li><a href="/pages/treningi.html">Treningi</a></li>
                            </ul>
                        </div><!-- .pad (end) -->
                </div><!-- .widget (end) -->
                <div class="widget">
                        <div class="pad">
                            <h3>Pozostałe</h3>
                           <ul>
                                <li><a href="/pages/rekrutacja.html">Rekrutacja</a></li>
                                <li><a href="/pages/osiagniecia.html">Osiągnięcia</a></li>
                                <li><a href="/galerie">Galeria zdjęć</a></li>
                            </ul>
                        </div><!-- .pad (end) -->
                </div><!-- .widget (end) -->
                <div class="widget contact">
                        <div class="pad">
                                <h3>Kontakt ze Szkołą</h3>
                                <ul class="jaybich-simple-contact">
                                        <li class="phone ie6">tel: +48 42 257-03-83</li>
                                        <li class="phone ie6">fax: +48 42 257-03-84</li>
                                        <li class="email ie6"><a href="mailto:sekretariat@smsbeachvolley.pl" title="Email Us">sekretariat@smsbeachvolley.pl</a></li>
                                        <li class="contact-form ie6"><a href="#" title="">Formularz kontaktowy</a></li>
                                        <li class="links ie6">
                                                <ul class="social-links">
                                                        <li><a href="#" title="RSS" class="rss ie6 image-button">RSS</a></li>
                                                        <li><a href="#" title="Twitter" class="twitter ie6 image-button">Twitter</a></li>
                                                        <li><a href="#" title="Facebook" class="facebook ie6 image-button">Facebook</a></li>
                                                        <li><a href="#" title="Myspace" class="myspace ie6 image-button">Myspace</a></li>
                                                        <li><a href="#" title="Flickr" class="flickr ie6 image-button">Flickr</a></li>
                                                        <li><a href="#" title="LinkedIn" class="linkedin ie6 image-button">LinkedIn</a></li>
                                                </ul>
                                        </li>
                                </ul>
                        </div><!-- .pad (end) -->
                </div><!-- .widget (end) -->
                <div class="clear"></div>
        </div><!-- #footer-widget-area-inner (end) -->
</div><!-- #footer-widget-area (end) -->

<!-- FOOTER (end) -->