<!-- MAIN MENU (start) -->
<div id="menu-wrapper" class="ie6">
    <?php echo str_replace(  'class="menu"', 'id="menu"', $this->navigation()->menu()->setUlClass('menu') ); ?>
    <!--<form method="get" id="searchform" action="">
            <div>
                    <input type="text" class="" value="" name="s" id="search-input" />
                    <input type="submit" class="ie6" id="searchsubmit" value="" />
            </div>
    </form>-->
</div><!-- menu-wrapper (end) -->

<!-- MAIN MENU (end) -->