<div id="slider">
        <div id="slider-image-shadow"></div>
        <ul>
                <li>
                        <a class="slider-link-current" href="http://www.siatka-lodzkie.org" title="Zobacz stronę Klubu Sympatyków Piłki Siatkowej"><span class="slider-link">Klub Sympatyków Piłki Siatkowej</span>
                                <img class="slider-image slider-image-current" alt="Klub Sympatyków Piłki Siatkowej" src="img/slider/5.jpg"/>
                                <span class="slider-caption slider-caption-current"></span>
                        </a>
                </li>
                <li>
                        <a href="http://tkkf-dzikusy.prv.pl/" title="TKKF Dzikusy"><span class="slider-link">TKKF Dzikusy</span>
                                <img class="slider-image" alt="Lorem ipsum" src="img/slider/9.jpg"/>
                                <span class="slider-caption"></span>
                        </a>
                </li>
                <li>
                        <a href="http://www.manufaktura.com/" title="Przejdź na stronę łódzkiej Manufaktury"><span class="slider-link">Manufaktura</span>
                                <img class="slider-image" alt="Lorem ipsum" src="img/slider/7.jpg"/>
                                <span class="slider-caption"></span>
                        </a>
                </li>
                <li>
                        <a href="http://plazowka-lodz.info/turnieje" title="Zobacz harmonogram turniejów"><span class="slider-link">Harmonogram turniejów</span>
                                <img class="slider-image" alt="Lorem ipsum" src="img/slider/8.jpg"/>
                                <span class="slider-caption"></span>
                        </a>
                </li>
                <li>
                        <a href="/pages/zgloszenia.html" title="Zgłoś się do turnieju"><span class="slider-link">Zgłoszenia do turniejów</span>
                                <img class="slider-image" alt="Zgłoś się do turnieju" src="img/slider/6.jpg"/>
                                <span class="slider-caption"></span>
                        </a>
                </li>
        </ul>

        <div id="slider-time-line">
                <div id="slider-time-line-current">
                </div>
        </div>

</div>