<div id="sub-header">
    <div id="slide-me">
    <a href="#"><img src="/img/slider/1.jpg" /><span><?php echo $this->title; ?></span></a>
    <a href="#"><img src="/img/slider/2.jpg" /><span><?php echo $this->title; ?></span></a>
    <a href="#"><img src="/img/slider/3.jpg" /><span><?php echo $this->title; ?></span></a>
    <a href="#"><img src="/img/slider/4.jpg" /><span><?php echo $this->title; ?></span></a>
    </div>
</div><!-- end sub-header -->