<?php

/**
 * Label
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Label extends BaseLabel
{
public static function getAll() {
        return Doctrine_Core::getTable( 'Label')->findAll();
    }

    public static function getLabelsArr() {
        $oLabels = self::getAll();
        $aReturn = array();
        foreach( $oLabels as $label ) {
            $aReturn[ $label->id ] = $label->Gname;
        }
        return $aReturn;
    }

    public static function getLabel( $name ) {
        return Doctrine_Core::getTable( 'Label' )->findOneByGname( $name );
    }
}