<?php

/**
 * Pageshistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Pageshistory extends BasePageshistory
{
    public function createBackup( $Pages_id, $content ) {
        $this->backedup = new Doctrine_Expression( "now()" );
        $this->content = $content;
        $this->backedup_by = Zend_Auth::getInstance()->getIdentity()->username;
        $this->Pages_id = $Pages_id;
        $this->save();
    }
}