<?php

/**
 * Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Tag extends BaseTag
{
 public static function makeTags( $tagsString ) {
        $aTranslate = array(
            ',' => '|',
            '.' => '|',
            ' ' => '|',
            ';' => '|',
            ':' => '|'
        );
        $tagsString = preg_replace("/[^a-zA-Z0-9ąęśćźżńół\-]+/iu", "|", strtr( strtolower( $tagsString ), $aTranslate ) );
        return explode( '|', $tagsString );
    }

    public static function checkIfExists( $tag ) {

        $aTag = Doctrine_Core::getTable( 'Tag' )->findByTname( $tag );
        if ( sizeof( $aTag ) == 0 ) {
            return false;
        } else {
            foreach( $aTag as $t ) {
                return $t;
            }
        }
        return false;
    }

    public static function checkTags( $aTags = array() ) {
        if ( !$aTags ) {
            return false;
        }
        $aReturn = array();

        foreach( $aTags as $tag ) {
            if ( $tag != '' ) {
                if ( ( $tagObj = self::checkIfExists( $tag ) ) !== false ) {
                    $aReturn[] = $tagObj;
                } else {
                    $tagObjNew = new Tag();
                    $tagObjNew->tname = $tag;
                    $tagObjNew->save();
                    $aReturn[] = $tagObjNew;
                }
            }
        }
        return $aReturn;
    }
}