<?php

/**
 * TagsRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class TagsRelation extends BaseTagsRelation
{
    public static function getRelations( $relID, $relName ) {
        return Doctrine_Core::getTable( 'TagsRelation' )->findByRel_idAndRelname( (int)$relID, $relName );
    }
}